#!/usr/bin/env python3
"""Build time_series_decomposed.ipynb: ratio product decomposition + dual-trajectory clustering.

Run from repo root: uv run python scripts/build_country_topic_catchup_decomposed_nb.py
"""
from __future__ import annotations

from pathlib import Path

import nbformat
import nbformat.v4 as nbf

ROOT = Path(__file__).resolve().parents[1]
OUT_NB = ROOT / "time_series_decomposed.ipynb"


def md(text: str):
    return nbf.new_markdown_cell(text)


def code(text: str):
    return nbf.new_code_cell(text)


cells: list = []

# =============================================================================
# §1 研究目标（新增分解框架）
# =============================================================================
cells.append(md(
    "## 1. 研究目标（Ratio 乘积分解 + 双维度聚类）\n\n"
    "对每个 **(国家, 主题)**，在多年份上观察相对研究前沿的强度（`ratio_to_frontier`），经 **时间滚动平滑** 后得到一条一维时间序列。\n\n"
    "### 当前比值的问题\n\n"
    "`ratio_to_frontier = share / frontier_value` 的比值上升可能有三种原因：\n\n"
    "| 原因 | 解释 | 政策含义 |\n"
    "|------|------|----------|\n"
    "| A. 本国份额增长 | **主动追赶** | 该国在此主题上有实质科研投入 |\n"
    "| B. 前沿国家份额萎缩 | **被动受益** | 前沿国家退出，该国相对\"被追赶\" |\n"
    "| C. 两者同时 | 混合效果 | 无法判断 |\n\n"
    "三种效果混在一起无法区分。\n\n"
    "### 乘积分解框架\n\n"
    "数学上，比值可以做如下分解：\n\n"
    "\\[ \\text{ratio}(t) = \\frac{\\text{share}(t)}{\\text{frontier}(t)} \\]\n\n"
    "取对数后：\n\n"
    "\\[ \\log\\ \\text{ratio}(t) = \\log\\ \\text{share}(t) - \\log\\ \\text{frontier}(t) \\]\n\n"
    "对时间求离散导数：\n\n"
    "\\[ \\Delta \\log\\ \\text{share}(t) = \\log\\ \\text{share}(t) - \\log\\ \\text{share}(t-1) \\]\n\n"
    "\\[ \\Delta \\log\\ \\text{frontier}(t) = \\log\\ \\text{frontier}(t) - \\log\\ \\text{frontier}(t-1) \\]\n\n"
    "由此可以将追赶分解为四个象限：\n\n"
    "| 象限 | 条件 | 类型 |\n"
    "|------|------|------|\n"
    "| I | Δshare > 0, Δfrontier > 0 | 共同扩张 |\n"
    "| II | Δshare < 0, Δfrontier > 0 | 失血型 |\n"
    "| III | Δshare < 0, Δfrontier < 0 | 前沿塌陷 |\n"
    "| **IV** | **Δshare > 0, Δfrontier < 0** | **主动追赶** |\n\n"
    "本 notebook 延续 `time_series_hierarchical.ipynb` 的层次聚类框架，但在以下三个维度独立聚类：\n"
    "- **聚类A**：对 `log_share` 轨迹聚类 → 识别份额增长模式\n"
    "- **聚类B**：对 `log_frontier` 轨迹聚类 → 识别前沿演变模式\n"
    "- **聚类C**：对 `[Δlog_share, Δlog_frontier]` 拼接向量聚类 → 联合分类\n\n"
    "**输出目录**：`output/time_series_hierarchical/`（`trajectory_*_decomposed*.csv/png` 等）。"
))

# =============================================================================
# §2 数据依赖
# =============================================================================
cells.append(md(
    "## 2. 数据依赖\n\n"
    "- **配置**：[`config/cluster_keybert_from_cluster.json`](config/cluster_keybert_from_cluster.json)"
    "（数据 CSV 路径、`paper_topics.csv` 所在目录、rolling 窗口与随机种子）。\n"
    "- **面板**：优先读取 `output/catchup_mvp/topic_country_year_panel.csv`（与 MVP 一致）；"
    "若不存在且 frontier 为 `top3_mean`，则从 `paper_topics.csv` 或配置中的主 CSV 重建。\n\n"
    "**内核**：建议使用仓库 `.venv`（含 `umap-learn`；**dtw** 模式另需 `tslearn`）。"
))

# =============================================================================
# §3 导入与路径
# =============================================================================
cells.append(code(
    'from __future__ import annotations\n'
    '\n'
    'import json\n'
    'import os\n'
    'import random\n'
    'import warnings\n'
    'from pathlib import Path\n'
    'from typing import Any, Literal\n'
    '\n'
    'import matplotlib.pyplot as plt\n'
    'import numpy as np\n'
    'import pandas as pd\n'
    'from sklearn.metrics import davies_bouldin_score, silhouette_score\n'
    'from sklearn.preprocessing import StandardScaler\n'
    '\n'
    '# 屏蔽部分库的未来弃用警告\n'
    "warnings.filterwarnings(\"ignore\", category=FutureWarning)\n"
    "warnings.filterwarnings(\"ignore\", category=RuntimeWarning)\n"
    '\n'
    "# --- 路径与输出目录 ---\n"
    '_CONFIG_PATH = Path("config/cluster_keybert_from_cluster.json")\n'
    'CATCHUP_MVP_DIR = Path("output/catchup_mvp")\n'
    'CATCHUP_ROUND2_DIR = Path("output/time_series_hierarchical")\n'
    'CATCHUP_ROUND2_DIR.mkdir(parents=True, exist_ok=True)\n'
    '\n'
    '\n'
    'def load_json_config(path: Path) -> dict[str, Any]:\n'
    '    """读取聚类流水线 JSON 配置。"""\n'
    '    with path.open("r", encoding="utf-8") as f:\n'
    '        return json.load(f)\n'
    '\n'
    '\n'
    'def set_reproducibility(seed: int) -> None:\n'
    '    """固定 Python / NumPy 随机种子。"""\n'
    '    random.seed(seed)\n'
    '    np.random.seed(seed)\n'
    '    os.environ["PYTHONHASHSEED"] = str(seed)\n'
    '\n'
    '\n'
    '_cfg = load_json_config(_CONFIG_PATH)\n'
    '_paths = _cfg["paths"]\n'
    'DATA_PATH = Path(_paths["data_csv"])\n'
    'CLUSTER_OUTPUT_DIR = Path(_paths["output_dir"])\n'
    'PAPER_TOPICS_PATH = CLUSTER_OUTPUT_DIR / "paper_topics.csv"\n'
    '_time = _cfg.get("time_evolution", {})\n'
    'CONFIG_ROLLING_WINDOW = int(_time.get("rolling_window_size", 5))\n'
    'CONFIG_ROLLING_MIN = int(_time.get("rolling_min_periods", 3))\n'
    'RANDOM_STATE = int(_cfg["reproducibility"]["seed"])\n'
    'set_reproducibility(RANDOM_STATE)\n'
    '\n'
    'print("CATCHUP_MVP_DIR exists:", CATCHUP_MVP_DIR.is_dir())\n'
    'print("CATCHUP_ROUND2_DIR:", CATCHUP_ROUND2_DIR.resolve())\n'
))

# =============================================================================
# §4 参数区
# =============================================================================
cells.append(md("## 4. 参数区（集中管理）"))

cells.append(code(
    '# 与配置中的随机种子一致\n'
    'RANDOM_STATE = RANDOM_STATE\n'
    '\n'
    '# 轨迹样本至少需要在多少年份上有发文，才进入聚类\n'
    'MIN_ACTIVE_YEARS = 6\n'
    '\n'
    '# 对 ratio_to_frontier 做滚动平均的窗口长度\n'
    'MAIN_ROLLING_WINDOW = CONFIG_ROLLING_WINDOW\n'
    'ROLLING_MIN_PERIODS = CONFIG_ROLLING_MIN\n'
    '\n'
    '# 前沿强度定义：top3_mean\n'
    'FRONTIER_TOP_K = 3\n'
    'MAIN_FRONTIER_MODE: Literal["top3_mean", "max"] = "top3_mean"\n'
    '\n'
    '# ---- 分解建模新增参数 ----\n'
    'DECOMP_LOG_ROLLING_WINDOW = 3\n'
    'DECOMP_LOG_ROLLING_MIN = 2\n'
    'DECOMP_DERIV_ROLLING_WINDOW = 3\n'
    'DECOMP_DERIV_ROLLING_MIN = 2\n'
    'QUADRANT_AGG_METHOD: Literal["mean", "median"] = "mean"\n'
    '\n'
    '# ---- 层次聚类参数 ----\n'
    'HIER_DISTANCE_MODE: Literal["euclidean", "dtw", "shape"] = "dtw"\n'
    'HIER_LINKAGE_METHOD: Literal["ward", "average", "complete", "single"] = "average"\n'
    'TRAJ_K_RANGE = range(2, 11)\n'
    '\n'
    'FINAL_K_STRATEGY: Literal["metrics_lex", "fixed"] = "metrics_lex"\n'
    'FINAL_K_OVERRIDE: int | None = None\n'
    '\n'
    '# 过滤弱信号单元\n'
    'MIN_PEAK_TOPIC_YEAR_SHARE = 0.05\n'
    'MIN_MEAN_SHARE_ACTIVE = 0.0\n'
    '\n'
    '# UMAP / t-SNE / PCA\n'
    'UMAP_N_NEIGHBORS = 30\n'
    'UMAP_MIN_DIST = 0.1\n'
    'TSNE_PERPLEXITY = 30\n'
    '\n'
    '# 数值稳定性\n'
    'FRONTIER_RATIO_EPS = 1e-10\n'
    'RATIO_ROLLING_MAX_CLIP = 50.0\n'
    'LOG_CLIP_MIN = -10.0\n'
    'LOG_CLIP_MAX = 0.0\n'
    '\n'
    '\n'
    'def validate_hierarchical_params(distance_mode: str, linkage_method: str) -> None:\n'
    '    """Validate HIER_DISTANCE_MODE x HIER_LINKAGE_METHOD combinations."""\n'
    '    if distance_mode not in ("euclidean", "dtw", "shape"):\n'
    '        raise ValueError(f"Invalid HIER_DISTANCE_MODE: {distance_mode!r}")\n'
    '    if linkage_method not in ("ward", "average", "complete", "single"):\n'
    '        raise ValueError(f"Invalid HIER_LINKAGE_METHOD: {distance_mode!r}")\n'
    '    if distance_mode in ("dtw", "shape") and linkage_method == "ward":\n'
    '        raise ValueError("ward linkage is not valid with precomputed DTW or shape distances.")\n'
    '\n'
    '\n'
    'validate_hierarchical_params(HIER_DISTANCE_MODE, HIER_LINKAGE_METHOD)\n'
    '\n'
    'plt.rcParams["figure.dpi"] = 120\n'
    'print(\n'
    '    "主要参数:",\n'
    '    "MAIN_ROLLING_WINDOW=", MAIN_ROLLING_WINDOW,\n'
    '    "DECOMP_LOG_ROLLING_WINDOW=", DECOMP_LOG_ROLLING_WINDOW,\n'
    '    "DECOMP_DERIV_ROLLING_WINDOW=", DECOMP_DERIV_ROLLING_WINDOW,\n'
    '    "HIER_DISTANCE_MODE=", HIER_DISTANCE_MODE,\n'
    '    "HIER_LINKAGE_METHOD=", HIER_LINKAGE_METHOD,\n'
    '    "TRAJ_K_RANGE=", list(TRAJ_K_RANGE),\n'
    '    "FINAL_K_STRATEGY=", FINAL_K_STRATEGY,\n'
    ')\n'
))

# =============================================================================
# §5 轨迹矩阵构建（扩展版）
# =============================================================================
cells.append(md(
    "## 5. 轨迹矩阵构建（扩展：原轨迹 + 分解轨迹）\n\n"
    "从面板得到每个 **(country, topic, year)** 的 `share` 与 `frontier_value`，"
    "经对数变换、rolling 平滑、离散导数后得到四套轨迹矩阵：\n\n"
    "| 矩阵 | 形状 | 含义 |\n"
    "|------|------|------|\n"
    "| `wide_log_share` | (n_units, n_years) | log(share) 滚动轨迹 |\n"
    "| `wide_log_frontier` | (n_units, n_years) | log(frontier_value) 滚动轨迹 |\n"
    "| `wide_dlog_share` | (n_units, n_years) | Δlog(share) 轨迹（年度份额增长率）|\n"
    "| `wide_dlog_frontier` | (n_units, n_years) | Δlog(frontier_value) 轨迹（前沿增长率）|\n\n"
    "**数值稳定**：对 `log(share)` 中 `share=0` 的单元格填充 `1e-10`，使对数有定义且不产生 `-inf`。\n"
    "导数轨迹通过 `[log(t) - log(t-1)]` 计算，再 rolling 平滑以压制单年噪声。"
))

cells.append(code(
    '# ---- 列名候选 ----\n'
    'TOPIC_CANDIDATES = ("topic", "Topic", "topic_id")\n'
    'YEAR_CANDIDATES = ("year", "Year", "pub_year", "publication_year")\n'
    'COUNTRY_CANDIDATES = ("country_code", "country", "Country", "nation")\n'
    '\n'
    '\n'
    'def _first_present(df: pd.DataFrame, names: tuple[str, ...]) -> str | None:\n'
    '    for n in names:\n'
    '        if n in df.columns:\n'
    '            return n\n'
    '    return None\n'
    '\n'
    '\n'
    'def resolve_topic_country_year_columns(df: pd.DataFrame) -> dict[str, str]:\n'
    '    out: dict[str, str] = {}\n'
    '    out["topic"] = _first_present(df, TOPIC_CANDIDATES) or ""\n'
    '    out["year"] = _first_present(df, YEAR_CANDIDATES) or ""\n'
    '    out["country_src"] = _first_present(df, COUNTRY_CANDIDATES) or ""\n'
    '    missing = [k for k, v in out.items() if not v]\n'
    '    if missing:\n'
    '        raise KeyError(f"Missing columns for: {missing}")\n'
    '    return out\n'
    '\n'
    '\n'
    'def load_paper_level_table() -> tuple[pd.DataFrame, str]:\n'
    '    """优先读聚类输出的 paper_topics；否则读配置中的主 CSV。"""\n'
    '    if PAPER_TOPICS_PATH.exists():\n'
    '        df = pd.read_csv(PAPER_TOPICS_PATH, low_memory=False)\n'
    '        return df, str(PAPER_TOPICS_PATH)\n'
    '    if not DATA_PATH.exists():\n'
    '        raise FileNotFoundError(\n'
    '            f"Neither {PAPER_TOPICS_PATH} nor {DATA_PATH} exists. "\n'
    '            "Run cluster_keybert_from_cluster.ipynb to export paper_topics.csv."\n'
    '        )\n'
    '    df = pd.read_csv(DATA_PATH, low_memory=False)\n'
    '    if _first_present(df, TOPIC_CANDIDATES) is None:\n'
    '        raise ValueError(f"No topic column in {DATA_PATH}.")\n'
    '    return df, str(DATA_PATH)\n'
    '\n'
    '\n'
    'def frontier_topk_mean_share(shares: pd.Series, k: int) -> float:\n'
    '    """在每个 (topic, year) 内，对各国 share 取 top-k 正的国家的均值。"""\n'
    '    s = shares.astype(float).sort_values(ascending=False)\n'
    '    s = s[s > 0] if (s > 0).any() else s\n'
    '    if s.empty:\n'
    '        return 0.0\n'
    '    top = s.head(min(k, len(s)))\n'
    '    return float(top.mean())\n'
    '\n'
    '\n'
    'def frontier_max_share(shares: pd.Series) -> float:\n'
    '    """备选前沿：该国在该主题该年的最大 share。"""\n'
    '    s = shares.astype(float)\n'
    '    if s.empty:\n'
    '        return 0.0\n'
    '    return float(s.max())\n'
    '\n'
    '\n'
    'def build_topic_country_year_panel_with_frontier(\n'
    '    papers: pd.DataFrame,\n'
    '    frontier_mode: Literal["top3_mean", "max"],\n'
    '    top_k: int,\n'
    ') -> pd.DataFrame:\n'
    '    """构造完整 (topic, country, year) 网格，计算 count、share、rank、frontier_value、ratio_to_frontier。"""\n'
    '    counts = (\n'
    '        papers.groupby(["topic", "country", "year"], observed=True)\n'
    '        .size()\n'
    '        .rename("count")\n'
    '        .reset_index()\n'
    '    )\n'
    '    topics = counts["topic"].unique()\n'
    '    countries = counts["country"].unique()\n'
    '    years = np.arange(int(counts["year"].min()), int(counts["year"].max()) + 1, dtype=int)\n'
    '    full = pd.MultiIndex.from_product(\n'
    '        [topics, countries, years], names=["topic", "country", "year"]\n'
    '    ).to_frame(index=False)\n'
    '    panel = full.merge(counts, on=["topic", "country", "year"], how="left")\n'
    '    panel["count"] = panel["count"].fillna(0).astype(int)\n'
    '    tot = panel.groupby(["topic", "year"])["count"].transform("sum")\n'
    '    panel["share"] = np.where(tot > 0, panel["count"] / tot, 0.0)\n'
    '    panel["rank"] = panel.groupby(["topic", "year"])["count"].rank(ascending=False, method="min")\n'
    '    if frontier_mode == "top3_mean":\n'
    '        panel["frontier_value"] = panel.groupby(["topic", "year"])["share"].transform(\n'
    '            lambda s: frontier_topk_mean_share(s, top_k)\n'
    '        )\n'
    '    elif frontier_mode == "max":\n'
    '        panel["frontier_value"] = panel.groupby(["topic", "year"])["share"].transform(frontier_max_share)\n'
    '    else:\n'
    '        raise ValueError(frontier_mode)\n'
    '    fv = panel["frontier_value"].astype(float)\n'
    '    sh = panel["share"].astype(float)\n'
    '    denom = np.maximum(fv, FRONTIER_RATIO_EPS)\n'
    '    panel["ratio_to_frontier"] = (sh / denom).astype(float)\n'
    '    panel["gap_to_frontier"] = panel["frontier_value"] - panel["share"]\n'
    '    return panel\n'
    '\n'
    '\n'
    'def load_or_build_panel(frontier_mode: str, top_k: int) -> tuple[pd.DataFrame, str]:\n'
    '    """若 MVP 已生成面板且模式为 top3_mean，则直接读取；否则从论文表重建。"""\n'
    '    mvp_panel = CATCHUP_MVP_DIR / "topic_country_year_panel.csv"\n'
    '    if mvp_panel.exists() and frontier_mode == "top3_mean":\n'
    '        panel = pd.read_csv(mvp_panel, low_memory=False)\n'
    '        if {"share", "frontier_value"}.issubset(panel.columns):\n'
    '            fv = panel["frontier_value"].astype(float)\n'
    '            sh = panel["share"].astype(float)\n'
    '            panel["ratio_to_frontier"] = (sh / np.maximum(fv, FRONTIER_RATIO_EPS)).astype(float)\n'
    '        src = f"read:{mvp_panel}"\n'
    '    else:\n'
    '        papers, _src = load_paper_level_table()\n'
    '        cols = resolve_topic_country_year_columns(papers)\n'
    '        tc, yc, csc = cols["topic"], cols["year"], cols["country_src"]\n'
    '        if csc != "country" and "country" in papers.columns:\n'
    '            papers = papers.drop(columns=["country"], errors="ignore")\n'
    '        papers = papers.rename(columns={tc: "topic", yc: "year", csc: "country"})\n'
    '        papers["topic"] = pd.to_numeric(papers["topic"], errors="coerce")\n'
    '        papers["year"] = pd.to_numeric(papers["year"], errors="coerce").astype("Int64")\n'
    '        papers = papers.dropna(subset=["topic", "year", "country"]).copy()\n'
    '        papers["topic"] = papers["topic"].astype(int)\n'
    '        papers["year"] = papers["year"].astype(int)\n'
    '        papers = papers[papers["topic"] != -1]\n'
    '        papers["country"] = papers["country"].astype(str).str.strip()\n'
    '        papers = papers[papers["country"].str.len() > 0]\n'
    '        panel = build_topic_country_year_panel_with_frontier(papers, frontier_mode, top_k)\n'
    '        src = f"rebuild:{frontier_mode}"\n'
    '        if not mvp_panel.exists():\n'
    '            out_rebuilt = CATCHUP_ROUND2_DIR / "topic_country_year_panel_rebuilt.csv"\n'
    '            panel.to_csv(out_rebuilt, index=False)\n'
    '            print("Saved rebuilt panel to", out_rebuilt)\n'
    '    return panel, src\n'
    '\n'
    '\n'
    'panel_main, panel_src = load_or_build_panel(MAIN_FRONTIER_MODE, FRONTIER_TOP_K)\n'
    'print("Panel source:", panel_src)\n'
    'print("shape", panel_main.shape, "cols", list(panel_main.columns))\n'
    'print(panel_main.head(3))\n'
    '\n'
    '\n'
    'def build_trajectory_matrix(\n'
    '    panel: pd.DataFrame,\n'
    '    years_all: np.ndarray,\n'
    '    rolling_window: int,\n'
    '    min_periods: int,\n'
    '    min_active_years: int,\n'
    '    min_peak_share: float | None = None,\n'
    '    min_mean_share_active: float | None = None,\n'
    ') -> tuple[pd.DataFrame, pd.DataFrame, pd.Series, pd.DataFrame]:\n'
    '    """由面板得到 rolling 后的 ratio 轨迹及辅助宽表。"""\n'
    '    year_cols = [str(y) for y in years_all]\n'
    '    thr = MIN_PEAK_TOPIC_YEAR_SHARE if min_peak_share is None else float(min_peak_share)\n'
    '    mthr = MIN_MEAN_SHARE_ACTIVE if min_mean_share_active is None else float(min_mean_share_active)\n'
    '    ratio_pivot = panel.pivot_table(\n'
    '        index=["country", "topic"], columns="year", values="ratio_to_frontier", aggfunc="first"\n'
    '    ).reindex(columns=years_all)\n'
    '    ratio_filled = ratio_pivot.fillna(0.0)\n'
    '    ratio_filled = pd.DataFrame(\n'
    '        np.nan_to_num(\n'
    '            ratio_filled.to_numpy(dtype=float, copy=True),\n'
    '            nan=0.0, posinf=RATIO_ROLLING_MAX_CLIP, neginf=0.0,\n'
    '        ),\n'
    '        index=ratio_filled.index,\n'
    '        columns=ratio_filled.columns,\n'
    '    )\n'
    '    roll = ratio_filled.T.rolling(rolling_window, min_periods=min_periods).mean().T.fillna(0.0)\n'
    '    roll = pd.DataFrame(\n'
    '        np.nan_to_num(\n'
    '            roll.to_numpy(dtype=float, copy=True),\n'
    '            nan=0.0, posinf=RATIO_ROLLING_MAX_CLIP, neginf=0.0,\n'
    '        ),\n'
    '        index=roll.index, columns=roll.columns,\n'
    '    )\n'
    '    count_pivot = (\n'
    '        panel.pivot_table(index=["country", "topic"], columns="year", values="count", aggfunc="first")\n'
    '        .reindex(columns=years_all).fillna(0).astype(int)\n'
    '    )\n'
    '    share_pivot = panel.pivot_table(\n'
    '        index=["country", "topic"], columns="year", values="share", aggfunc="first"\n'
    '    ).reindex(columns=years_all)\n'
    '    peak_share = share_pivot.max(axis=1).fillna(0.0)\n'
    '    mask_peak = peak_share >= thr\n'
    '    active_years = (count_pivot > 0).sum(axis=1)\n'
    '    mask_active = active_years >= min_active_years\n'
    '    ps_active = peak_share.reindex(active_years.index).fillna(0.0)\n'
    '    print("peak_share among active_years-eligible units:\\n",\n'
    '          ps_active.loc[mask_active].describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.9]))\n'
    '    count_pos = count_pivot > 0\n'
    '    mean_share_active = share_pivot.where(count_pos).mean(axis=1).fillna(0.0)\n'
    '    if mthr > 0:\n'
    '        mean_ok = mean_share_active.reindex(active_years.index).fillna(0.0) >= mthr\n'
    '    else:\n'
    '        mean_ok = pd.Series(True, index=active_years.index)\n'
    '    peak_ok = mask_peak.reindex(active_years.index).fillna(False)\n'
    '    mask = mask_active & peak_ok & mean_ok\n'
    '    n_active = int(mask_active.sum())\n'
    '    n_final = int(mask.sum())\n'
    '    n_drop_peak = int((mask_active & ~peak_ok).sum())\n'
    '    n_drop_mean = int((mask_active & peak_ok & ~mean_ok).sum()) if mthr > 0 else 0\n'
    '    print(\n'
    '        f"Trajectory filter: active_years>={min_active_years}: {n_active}, "\n'
    '        f"after peak_share>={thr}: {n_final}, "\n'
    '        f"dropped_by_peak_only: {n_drop_peak}, dropped_by_mean_only: {n_drop_mean}"\n'
    '    )\n'
    '    wide_roll = roll.loc[mask].copy()\n'
    '    wide_roll.columns = year_cols\n'
    '    wide_ratio = ratio_filled.loc[mask].copy()\n'
    '    wide_ratio.columns = year_cols\n'
    '    active_f = active_years.loc[mask]\n'
    '    count_sub = count_pivot.loc[mask].copy()\n'
    '    count_sub.columns = year_cols\n'
    '    return wide_roll, wide_ratio, active_f, count_sub\n'
    '\n'
    '\n'
    'years_all = np.sort(panel_main["year"].unique())\n'
    'year_cols = [str(y) for y in years_all]\n'
    '\n'
    '# 原始 ratio 轨迹（与 hierarchical notebook 完全一致）\n'
    'wide_roll_raw, wide_ratio_raw, active_years_s, count_wide = build_trajectory_matrix(\n'
    '    panel_main, years_all, MAIN_ROLLING_WINDOW, ROLLING_MIN_PERIODS, MIN_ACTIVE_YEARS\n'
    ')\n'
    'meta = wide_roll_raw.reset_index()[["country", "topic"]]\n'
    'print("Trajectory units:", len(wide_roll_raw), "T:", wide_roll_raw.shape[1],\n'
    '      "years", years_all[0], "..", years_all[-1])\n'
))

# =============================================================================
# §6 Ratio 乘积分解轨迹
# =============================================================================
cells.append(md(
    "## 6. Ratio 乘积分解轨迹\n\n"
    "从面板的 `share` 和 `frontier_value` 列出发，构建四套轨迹矩阵：\n\n"
    "1. **log_share**: `log(max(share, 1e-10))`，rolling 平滑后 clip 到 `[LOG_CLIP_MIN, LOG_CLIP_MAX]`\n"
    "2. **log_frontier**: 同上，但应用于 `frontier_value`\n"
    "3. **Δlog_share**: 相邻年份 `log_share` 差分，再 rolling 平滑\n"
    "4. **Δlog_frontier**: 相邻年份 `log_frontier` 差分，再 rolling 平滑\n\n"
    "这样每一套轨迹都是 **(n_units, n_years)** 的 DataFrame，行索引与 `meta`（country, topic）一致。"
))

cells.append(code(
    'def build_log_decomposition_trajectories(\n'
    '    panel: pd.DataFrame,\n'
    '    years_all: np.ndarray,\n'
    '    log_rolling_window: int,\n'
    '    log_rolling_min: int,\n'
    '    deriv_rolling_window: int,\n'
    '    deriv_rolling_min: int,\n'
    '    mask: pd.Series | None = None,\n'
    ') -> dict[str, pd.DataFrame]:\n'
    '    """\n'
    '    构建 log(share)、log(frontier)、Δlog(share)、Δlog(frontier) 四套轨迹。\n'
    '    \n'
    '    Returns\n'
    '    -------\n'
    '    dict[str, pd.DataFrame]: wide_log_share, wide_log_frontier, \n'
    '        wide_dlog_share, wide_dlog_frontier, has_activity_mask\n'
    '    """\n'
    '    year_cols = [str(y) for y in years_all]\n'
    '\n'
    '    # share 和 frontier_value 透视表\n'
    '    share_pivot = panel.pivot_table(\n'
    '        index=["country", "topic"], columns="year", values="share", aggfunc="first"\n'
    '    ).reindex(columns=years_all)\n'
    '    frontier_pivot = panel.pivot_table(\n'
    '        index=["country", "topic"], columns="year", values="frontier_value", aggfunc="first"\n'
    '    ).reindex(columns=years_all)\n'
    '\n'
    '    # 有发文的国家-主题对\n'
    '    count_pivot = (\n'
    '        panel.pivot_table(index=["country", "topic"], columns="year", values="count", aggfunc="first")\n'
    '        .reindex(columns=years_all).fillna(0).astype(int)\n'
    '    )\n'
    '    has_activity = count_pivot > 0\n'
    '\n'
    '    if mask is not None:\n'
    '        share_pivot = share_pivot.loc[mask]\n'
    '        frontier_pivot = frontier_pivot.loc[mask]\n'
    '        has_activity = has_activity.loc[mask]\n'
    '\n'
    '    # ---- 1. log_share: share in (0,1], log in (-inf, 0] ----\n'
    '    # share=0 填充极小正值，使 log 有定义\n'
    '    share_filled = share_pivot.fillna(0.0).clip(lower=1e-10, upper=1.0 - 1e-15)\n'
    '    log_share_raw = np.log(share_filled)\n'
    '    log_share_clipped = log_share_raw.clip(LOG_CLIP_MIN, LOG_CLIP_MAX)\n'
    '    log_share_roll = (\n'
    '        log_share_clipped.T.rolling(log_rolling_window, min_periods=log_rolling_min)\n'
    '        .mean().T.fillna(0.0)\n'
    '    )\n'
    '    wide_log_share = log_share_roll.copy()\n'
    '    wide_log_share.columns = year_cols\n'
    '\n'
    '    # ---- 2. log_frontier ----\n'
    '    frontier_filled = frontier_pivot.fillna(0.0).clip(lower=1e-10, upper=1.0)\n'
    '    log_frontier_raw = np.log(frontier_filled)\n'
    '    log_frontier_clipped = log_frontier_raw.clip(LOG_CLIP_MIN, LOG_CLIP_MAX)\n'
    '    log_frontier_roll = (\n'
    '        log_frontier_clipped.T.rolling(log_rolling_window, min_periods=log_rolling_min)\n'
    '        .mean().T.fillna(0.0)\n'
    '    )\n'
    '    wide_log_frontier = log_frontier_roll.copy()\n'
    '    wide_log_frontier.columns = year_cols\n'
    '\n'
    '    # ---- 3. Δlog_share: 年度份额增长率 ----\n'
    '    any_activity = has_activity.any(axis=1)\n'
    '    _share_for_diff = wide_log_share.loc[any_activity]\n'
    '    dlog_share_raw = _share_for_diff.diff(axis=1)\n'
    '    dlog_share_roll = (\n'
    '        dlog_share_raw.T.rolling(deriv_rolling_window, min_periods=deriv_rolling_min)\n'
    '        .mean().T.fillna(0.0)\n'
    '    )\n'
    '    wide_dlog_share = dlog_share_roll.copy()\n'
    '    wide_dlog_share.columns = year_cols\n'
    '\n'
    '    # 对没有活动的单元填零保持对齐\n'
    '    if (~any_activity).any():\n'
    '        wide_dlog_share = pd.concat([\n'
    '            wide_dlog_share,\n'
    '            pd.DataFrame(0.0, index=list(~any_activity), columns=year_cols),\n'
    '        ]).loc[wide_dlog_share.index]\n'
    '\n'
    '    # ---- 4. Δlog_frontier ----\n'
    '    _frontier_for_diff = wide_log_frontier.loc[any_activity]\n'
    '    dlog_frontier_raw = _frontier_for_diff.diff(axis=1)\n'
    '    dlog_frontier_roll = (\n'
    '        dlog_frontier_raw.T.rolling(deriv_rolling_window, min_periods=deriv_rolling_min)\n'
    '        .mean().T.fillna(0.0)\n'
    '    )\n'
    '    wide_dlog_frontier = dlog_frontier_roll.copy()\n'
    '    wide_dlog_frontier.columns = year_cols\n'
    '\n'
    '    if (~any_activity).any():\n'
    '        wide_dlog_frontier = pd.concat([\n'
    '            wide_dlog_frontier,\n'
    '            pd.DataFrame(0.0, index=list(~any_activity), columns=year_cols),\n'
    '        ]).loc[wide_dlog_frontier.index]\n'
    '\n'
    '    return {\n'
    '        "wide_log_share": wide_log_share,\n'
    '        "wide_log_frontier": wide_log_frontier,\n'
    '        "wide_dlog_share": wide_dlog_share,\n'
    '        "wide_dlog_frontier": wide_dlog_frontier,\n'
    '        "has_activity_mask": any_activity,\n'
    '    }\n'
    '\n'
    '\n'
    '# ---- 计算四套分解轨迹 ----\n'
    'decomp = build_log_decomposition_trajectories(\n'
    '    panel_main, years_all,\n'
    '    DECOMP_LOG_ROLLING_WINDOW, DECOMP_LOG_ROLLING_MIN,\n'
    '    DECOMP_DERIV_ROLLING_WINDOW, DECOMP_DERIV_ROLLING_MIN,\n'
    '    mask=wide_roll_raw.index,\n'
    ')\n'
    '\n'
    'wide_log_share = decomp["wide_log_share"]\n'
    'wide_log_frontier = decomp["wide_log_frontier"]\n'
    'wide_dlog_share = decomp["wide_dlog_share"]\n'
    'wide_dlog_frontier = decomp["wide_dlog_frontier"]\n'
    'any_activity = decomp["has_activity_mask"]\n'
    '\n'
    'print("wide_log_share shape:", wide_log_share.shape)\n'
    'print("wide_log_frontier shape:", wide_log_frontier.shape)\n'
    'print("wide_dlog_share shape:", wide_dlog_share.shape)\n'
    'print("wide_dlog_frontier shape:", wide_dlog_frontier.shape)\n'
    'print("log_share range check: min=",\n'
    '      wide_log_share.values.min(), "max=", wide_log_share.values.max())\n'
))

# =============================================================================
# §7 分解轨迹可视化与象限分析
# =============================================================================
cells.append(md(
    "## 7. 分解轨迹可视化与象限分析\n\n"
    "在每个 (country, topic) 单元上，取其在**有发文年份**上的时间均值作为代表值：\n\n"
    "- `mean_dlog_share` = Δlog_share 在有发文年份上的均值\n"
    "- `mean_dlog_frontier` = Δlog_frontier 在有发文年份上的均值\n\n"
    "以 `(mean_dlog_share, mean_dlog_frontier)` 做散点图，按象限着色：\n\n"
    "- **象限 IV**（右上）：`mean_dlog_share > 0` 且 `mean_dlog_frontier < 0` → **主动追赶**\n"
    "- **象限 II**（左上）：`mean_dlog_share < 0` 且 `mean_dlog_frontier > 0` → **失血型**\n"
    "- **象限 I**（左下）：两者均负 → 前沿塌陷\n"
    "- **象限 III**（右下）：两者均正 → 共同扩张\n\n"
    "象限分界线取各指标的中位数（而非 0），以避免少数极端年份主导判定。"
))

cells.append(code(
    'def plot_quadrant_analysis(\n'
    '    wide_dlog_share: pd.DataFrame,\n'
    '    wide_dlog_frontier: pd.DataFrame,\n'
    '    meta_df: pd.DataFrame,\n'
    '    agg_method: str,\n'
    '    out_path: Path,\n'
    '    title: str,\n'
    ') -> pd.DataFrame:\n'
    '    """散点图: mean Δlog_share vs mean Δlog_frontier，按四象限着色。"""\n'
    '    mean_dlog_share = wide_dlog_share.mean(axis=1).rename("mean_dlog_share")\n'
    '    mean_dlog_frontier = wide_dlog_frontier.mean(axis=1).rename("mean_dlog_frontier")\n'
    '\n'
    '    df_quad = pd.DataFrame({\n'
    '        "country": meta_df["country"].values,\n'
    '        "topic": meta_df["topic"].values,\n'
    '        "mean_dlog_share": mean_dlog_share.values,\n'
    '        "mean_dlog_frontier": mean_dlog_frontier.values,\n'
    '    })\n'
    '\n'
    '    # 中位数分界线\n'
    '    med_share = df_quad["mean_dlog_share"].median()\n'
    '    med_frontier = df_quad["mean_dlog_frontier"].median()\n'
    '\n'
    '    # 象限标签\n'
    '    def quadrant(row):\n'
    '        ds = row["mean_dlog_share"]\n'
    '        df_val = row["mean_dlog_frontier"]\n'
    '        if ds > 0 and df_val < 0:\n'
    '            return "IV: Active Catch-up"\n'
    '        elif ds < 0 and df_val > 0:\n'
    '            return "II: Hemorrhaging"\n'
    '        elif ds < 0 and df_val < 0:\n'
    '            return "III: Frontier Collapse"\n'
    '        else:\n'
    '            return "I: Co-expansion"\n'
    '\n'
    '    df_quad["quadrant"] = df_quad.apply(quadrant, axis=1)\n'
    '\n'
    '    # 绘图\n'
    '    fig, ax = plt.subplots(figsize=(8, 7))\n'
    '    colors = {\n'
    '        "IV: Active Catch-up": "#2ecc71",\n'
    '        "II: Hemorrhaging": "#e74c3c",\n'
    '        "III: Frontier Collapse": "#9b59b6",\n'
    '        "I: Co-expansion": "#3498db",\n'
    '    }\n'
    '    for q, grp in df_quad.groupby("quadrant"):\n'
    '        ax.scatter(\n'
    '            grp["mean_dlog_share"], grp["mean_dlog_frontier"],\n'
    '            c=colors.get(q, "gray"), s=20, alpha=0.65,\n'
    '            label=f"{q} (n={len(grp)})",\n'
    '        )\n'
    '\n'
    '    ax.axvline(med_share, color="gray", ls="--", lw=0.8, alpha=0.6)\n'
    '    ax.axhline(med_frontier, color="gray", ls="--", lw=0.8, alpha=0.6)\n'
    '    ax.set_xlabel("Mean Δlog(share) - Country share growth rate")\n'
    '    ax.set_ylabel("Mean Δlog(frontier) - Frontier change rate")\n'
    '    ax.set_title(\n'
    '        f"{title}\\n(medians: Δshare={med_share:.4f}, Δfrontier={med_frontier:.4f})"\n'
    '    )\n'
    '    ax.legend(fontsize=8, ncol=2)\n'
    '    fig.tight_layout()\n'
    '    fig.savefig(out_path, dpi=160)\n'
    '    plt.close(fig)\n'
    '\n'
    '    print("Quadrant distribution:")\n'
    '    print(df_quad["quadrant"].value_counts())\n'
    '    return df_quad\n'
    '\n'
    '\n'
    'def plot_decomposition_timeseries(\n'
    '    wide_log_share: pd.DataFrame,\n'
    '    wide_log_frontier: pd.DataFrame,\n'
    '    years: np.ndarray,\n'
    '    labels: np.ndarray | None,\n'
    '    out_path: Path,\n'
    '    title: str,\n'
    '    n_show: int = 20,\n'
    ') -> None:\n'
    '    """并排展示 log_share 和 log_frontier 时间序列。"""\n'
    '    n_clusters = int(labels.max()) + 1 if labels is not None else 1\n'
    '    fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n'
    '    for ax, wide_arr, ylabel in zip(\n'
    '        axes, [wide_log_share, wide_log_frontier], ["log(share)", "log(frontier_value)"],\n'
    '    ):\n'
    '        if labels is not None:\n'
    '            for c in range(n_clusters):\n'
    '                mask_c = labels == c\n'
    '                sub = wide_arr.values[mask_c]\n'
    '                idx_show = np.random.choice(\n'
    '                    len(sub), min(n_show // n_clusters, len(sub)), replace=False\n'
    '                )\n'
    '                for idx in idx_show:\n'
    '                    ax.plot(years, sub[idx], alpha=0.15, color=f"C{c}")\n'
    '                ax.plot(years, sub.mean(axis=0), color=f"C{c}", lw=2,\n'
    '                        label=f"C{c} mean (n={mask_c.sum()})")\n'
    '        else:\n'
    '            sub = wide_arr.values\n'
    '            idx_show = np.random.choice(len(sub), min(n_show, len(sub)), replace=False)\n'
    '            for idx in idx_show:\n'
    '                ax.plot(years, sub[idx], alpha=0.2, color="steelblue")\n'
    '            ax.plot(years, sub.mean(axis=0), color="navy", lw=2, label="Overall mean")\n'
    '        ax.set_xlabel("Year")\n'
    '        ax.set_ylabel(ylabel)\n'
    '        ax.legend(fontsize=7)\n'
    '    fig.suptitle(title, y=1.02)\n'
    '    fig.tight_layout()\n'
    '    fig.savefig(out_path, dpi=160, bbox_inches="tight")\n'
    '    plt.close(fig)\n'
    '\n'
    '\n'
    '# ---- 象限分析图 ----\n'
    'quadrant_df = plot_quadrant_analysis(\n'
    '    wide_dlog_share, wide_dlog_frontier, meta,\n'
    '    QUADRANT_AGG_METHOD,\n'
    '    CATCHUP_ROUND2_DIR / "trajectory_quadrant_decomposed.png",\n'
    '    "Ratio Decomposition Quadrant Analysis (decomposed)",\n'
    ')\n'
    '\n'
    '# ---- log_share / log_frontier 并行时间序列 ----\n'
    'plot_decomposition_timeseries(\n'
    '    wide_log_share, wide_log_frontier, years_all,\n'
    '    labels=None,\n'
    '    out_path=CATCHUP_ROUND2_DIR / "trajectory_decomposed_timeseries.png",\n'
    '    title="log(share) and log(frontier) trajectories",\n'
    ')\n'
    '\n'
    'print("Decomposition visualization done.")\n'
))

# =============================================================================
# §8 层次聚类（三套轨迹独立聚类）
# =============================================================================
cells.append(md(
    "## 8. 层次聚类（三套轨迹独立聚类）\n\n"
    "对以下三套轨迹分别做层次聚类：\n\n"
    "| 聚类集 | 轨迹输入 | 聚类目标 |\n"
    "|--------|---------|----------|\n"
    "| **聚类A** | `wide_log_share` | 识别**份额增长**模式 |\n"
    "| **聚类B** | `wide_log_frontier` | 识别**前沿演变**模式 |\n"
    "| **聚类C** | `[wide_dlog_share, wide_dlog_frontier]` 拼接 | 联合分类（主动/被动）|\n\n"
    "每套聚类独立选 k（metrics_lex 策略），独立输出 CSV / PNG。"
))

cells.append(code(
    '# =============================================================================\n'
    '# 工具函数（复用 hierarchical 的核心逻辑）\n'
    '# =============================================================================\n'
    '\n'
    'def z_normalize_rows(wide_roll: pd.DataFrame) -> np.ndarray:\n'
    '    """Per-row z-score; constant rows become zeros."""\n'
    '    X = wide_roll.to_numpy(dtype=float, copy=True)\n'
    '    mu = np.nanmean(X, axis=1, keepdims=True)\n'
    '    sig = np.nanstd(X, axis=1, ddof=0, keepdims=True)\n'
    '    bad = ~np.isfinite(sig) | (sig < 1e-12)\n'
    '    Z = (X - mu) / np.where(bad, 1.0, sig)\n'
    '    Z = np.where(bad, 0.0, Z)\n'
    '    Z = np.nan_to_num(Z, nan=0.0, posinf=0.0, neginf=0.0)\n'
    '    return Z\n'
    '\n'
    '\n'
    'def build_pairwise_distance_matrix(\n'
    '    wide_roll: pd.DataFrame, distance_mode: str\n'
    ') -> tuple[np.ndarray | None, np.ndarray]:\n'
    '    """Build precomputed distance matrix and feature matrix."""\n'
    '    X_raw = wide_roll.to_numpy(dtype=float, copy=False)\n'
    '    if distance_mode == "euclidean":\n'
    '        X_used = StandardScaler().fit_transform(X_raw)\n'
    '        return None, X_used\n'
    '    if distance_mode == "dtw":\n'
    '        try:\n'
    '            from tslearn.metrics import cdist_dtw\n'
    '        except ImportError as e:\n'
    '            raise ImportError(\n'
    '                "tslearn is required for HIER_DISTANCE_MODE=\'dtw\'. "\n'
    '                "Install with: uv add tslearn"\n'
    '            ) from e\n'
    '        X_used = StandardScaler().fit_transform(X_raw)\n'
    '        X3 = X_raw[:, :, np.newaxis]\n'
    '        D = np.asarray(cdist_dtw(X3, X3), dtype=float)\n'
    '        D = (D + D.T) * 0.5\n'
    '        np.fill_diagonal(D, 0.0)\n'
    '        D = np.nan_to_num(D, nan=0.0, posinf=0.0, neginf=0.0)\n'
    '        return D, X_used\n'
    '    if distance_mode == "shape":\n'
    '        Z = z_normalize_rows(wide_roll)\n'
    '        X_used = Z\n'
    '        with np.errstate(invalid="ignore"):\n'
    '            C = np.corrcoef(Z)\n'
    '        D = 1.0 - C\n'
    '        np.fill_diagonal(D, 0.0)\n'
    '        D = np.nan_to_num(D, nan=1.0, posinf=1.0, neginf=1.0)\n'
    '        D = (D + D.T) * 0.5\n'
    '        np.fill_diagonal(D, 0.0)\n'
    '        D = np.clip(D, 0.0, 2.0)\n'
    '        return D, X_used\n'
    '    raise ValueError(distance_mode)\n'
    '\n'
    '\n'
    'def fit_hierarchical_single_k(\n'
    '    wide_roll: pd.DataFrame,\n'
    '    k: int,\n'
    '    distance_mode: str,\n'
    '    linkage_method: str,\n'
    '    D: np.ndarray | None,\n'
    '    X_used: np.ndarray,\n'
    ') -> np.ndarray:\n'
    '    """Fit one AgglomerativeClustering with k clusters."""\n'
    '    from sklearn.cluster import AgglomerativeClustering\n'
    '\n'
    '    n = len(wide_roll)\n'
    '    if k < 2 or k >= n:\n'
    '        raise ValueError(f"invalid k={k} for n={n}")\n'
    '    if distance_mode == "euclidean":\n'
    '        model = AgglomerativeClustering(\n'
    '            n_clusters=k, metric="euclidean", linkage=linkage_method\n'
    '        )\n'
    '    else:\n'
    '        model = AgglomerativeClustering(\n'
    '            n_clusters=k, metric="precomputed", linkage=linkage_method\n'
    '        )\n'
    '    labels = model.fit_predict(D if D is not None else X_used)\n'
    '    labels = np.asarray(labels, dtype=int)\n'
    '    uniq = np.unique(labels)\n'
    '    if len(uniq) != len(np.arange(uniq.min(), uniq.max() + 1)):\n'
    '        labels = pd.factorize(labels, sort=True)[0].astype(int)\n'
    '    return labels\n'
    '\n'
    '\n'
    'def score_labels_flat(X_flat: np.ndarray, labels: np.ndarray) -> tuple[float, float]:\n'
    '    """DB and silhouette on flat Euclidean space."""\n'
    '    uq = np.unique(labels)\n'
    '    if len(uq) < 2 or len(X_flat) < uq.max() + 2:\n'
    '        return np.inf, np.nan\n'
    '    with warnings.catch_warnings():\n'
    '        warnings.simplefilter("ignore", category=RuntimeWarning)\n'
    '        try:\n'
    '            sil = float(silhouette_score(X_flat, labels, metric="euclidean"))\n'
    '        except Exception:\n'
    '            sil = np.nan\n'
    '        db = float(davies_bouldin_score(X_flat, labels))\n'
    '    return db, sil\n'
    '\n'
    '\n'
    'def cluster_size_entropy(labels: np.ndarray) -> float:\n'
    '    vc = pd.Series(labels).value_counts(normalize=True)\n'
    '    return float(-(vc * np.log(vc + 1e-15)).sum())\n'
    '\n'
    '\n'
    'def hierarchical_search_all_k(\n'
    '    wide_roll: pd.DataFrame,\n'
    '    k_list: list[int],\n'
    '    distance_mode: str,\n'
    '    linkage_method: str,\n'
    ') -> tuple[pd.DataFrame, np.ndarray | None, np.ndarray]:\n'
    '    """Search all k and return metrics DataFrame."""\n'
    '    D, X_used = build_pairwise_distance_matrix(wide_roll, distance_mode)\n'
    '    X_score = X_used\n'
    '    n = len(wide_roll)\n'
    '    rows: list[dict[str, Any]] = []\n'
    '    for k in k_list:\n'
    '        if k < 2 or k >= n:\n'
    '            rows.append({"k": k, "error": "k_out_of_range"})\n'
    '            continue\n'
    '        try:\n'
    '            labels = fit_hierarchical_single_k(\n'
    '                wide_roll, k, distance_mode, linkage_method, D, X_used\n'
    '            )\n'
    '            uq = np.unique(labels)\n'
    '            if len(uq) < 2:\n'
    '                raise ValueError("single_cluster")\n'
    '            db, sil = score_labels_flat(X_score, labels)\n'
    '            sizes = pd.Series(labels).value_counts().sort_index()\n'
    '            sz_str = ",".join(f"{int(i)}:{int(sizes.loc[i])}" for i in sizes.index)\n'
    '            rows.append({\n'
    '                "k": k, "db": db, "silhouette": sil,\n'
    '                "cluster_sizes": sz_str,\n'
    '                "size_entropy": cluster_size_entropy(labels),\n'
    '                "distance_mode": distance_mode,\n'
    '                "linkage_method": linkage_method,\n'
    '            })\n'
    '        except Exception as e:\n'
    '            rows.append({"k": k, "error": str(e)})\n'
    '    return pd.DataFrame(rows), D, X_used\n'
    '\n'
    '\n'
    'def pick_best_k_from_metrics(\n'
    '    metrics_df: pd.DataFrame, strategy: str, override: int | None, n_samples: int\n'
    ') -> tuple[int, str]:\n'
    '    """Select k: metrics_lex = min(db, -silhouette); fixed = override."""\n'
    '    if strategy == "fixed":\n'
    '        if override is None:\n'
    '            raise ValueError("FINAL_K_STRATEGY=fixed requires FINAL_K_OVERRIDE")\n'
    '        kf = int(override)\n'
    '        ok_k = set(metrics_df.loc[metrics_df["db"].notna(), "k"].astype(int))\n'
    '        if kf not in ok_k:\n'
    '            raise ValueError(f"k={kf} not found in search results")\n'
    '        return kf, "fixed"\n'
    '    sub = metrics_df.loc[metrics_df["db"].notna()].copy()\n'
    '    if sub.empty:\n'
    '        raise RuntimeError("no valid k for metrics_lex")\n'
    '    sub["_neg_sil"] = -np.nan_to_num(sub["silhouette"].astype(float), nan=-1e9)\n'
    '    sub = sub.sort_values(["db", "_neg_sil", "k"])\n'
    '    return int(sub.iloc[0]["k"]), "metrics_lex"\n'
    '\n'
    '\n'
    'def plot_hier_k_diagnostics(\n'
    '    metrics_df: pd.DataFrame, k_final: int | None, out_path: Path, title: str\n'
    ') -> None:\n'
    '    sub = metrics_df.loc[metrics_df["db"].notna()].sort_values("k")\n'
    '    if sub.empty:\n'
    '        warnings.warn("No valid k rows; skipping diagnostics plot")\n'
    '        return\n'
    '    fig, axes = plt.subplots(1, 2, figsize=(9, 3.5))\n'
    '    ax0, ax1 = axes\n'
    '    ax0.plot(sub["k"], sub["db"], "o-", color="C1", lw=1.2)\n'
    '    ax0.set_xlabel("k"); ax0.set_ylabel("Davies-Bouldin"); ax0.set_title("DB index")\n'
    '    ax1.plot(sub["k"], sub["silhouette"].astype(float), "o-", color="C2", lw=1.2)\n'
    '    ax1.set_xlabel("k"); ax1.set_ylabel("Silhouette"); ax1.set_title("Silhouette")\n'
    '    if k_final is not None:\n'
    '        for ax in axes:\n'
    '            ax.axvline(k_final, color="crimson", ls="--", lw=1.0, alpha=0.85,\n'
    '                       label=f"k_final={k_final}")\n'
    '            ax.legend(fontsize=7)\n'
    '    fig.suptitle(title, y=1.02)\n'
    '    fig.tight_layout()\n'
    '    fig.savefig(out_path, dpi=160, bbox_inches="tight")\n'
    '    plt.close(fig)\n'
    '\n'
    '\n'
    'def plot_prototypes_single(\n'
    '    wide_roll: pd.DataFrame,\n'
    '    labels: np.ndarray,\n'
    '    years: np.ndarray,\n'
    '    out_path: Path,\n'
    '    title: str,\n'
    '    ylabel: str = "Mean rolling value",\n'
    ') -> None:\n'
    '    """Mean trajectory per cluster."""\n'
    '    clusters = np.sort(np.unique(labels))\n'
    '    fig, ax = plt.subplots(figsize=(10, 5))\n'
    '    for c in clusters:\n'
    '        idx = labels == c\n'
    '        mean_curve = wide_roll.values[idx].mean(axis=0)\n'
    '        ax.plot(years, mean_curve, label=f"C{int(c)} (n={int(idx.sum())})")\n'
    '    ax.axhline(0.0, color="gray", ls="--", lw=0.8)\n'
    '    ax.set_xlabel("Year"); ax.set_ylabel(ylabel)\n'
    '    ax.set_title(title)\n'
    '    ax.legend(fontsize=8, ncol=2)\n'
    '    fig.tight_layout()\n'
    '    fig.savefig(out_path, dpi=160)\n'
    '    plt.close(fig)\n'
    '\n'
    '\n'
    'def fit_2d_embeddings(\n'
    '    wide_roll: pd.DataFrame,\n'
    '    random_state: int,\n'
    ') -> dict[str, Any]:\n'
    '    """UMAP / t-SNE / PCA on scaled rolling features."""\n'
    '    from sklearn.decomposition import PCA\n'
    '    from sklearn.manifold import TSNE\n'
    '    from umap import UMAP\n'
    '\n'
    '    X = StandardScaler().fit_transform(wide_roll.values.astype(float))\n'
    '    n = X.shape[0]\n'
    '    out_umap = np.full((n, 2), np.nan)\n'
    '    out_tsne = np.full((n, 2), np.nan)\n'
    '    out_pca = np.full((n, 2), np.nan)\n'
    '    tsne_perp: int | None = None\n'
    '    pca_var_pct: float | None = None\n'
    '    if n >= 3:\n'
    '        pca = PCA(n_components=2)\n'
    '        out_pca = pca.fit_transform(X)\n'
    '        pca_var_pct = 100.0 * float(np.sum(pca.explained_variance_ratio_))\n'
    '    if n >= 5:\n'
    '        nn = max(2, min(UMAP_N_NEIGHBORS, n - 1))\n'
    '        out_umap = UMAP(\n'
    '            n_components=2, n_neighbors=nn, min_dist=UMAP_MIN_DIST,\n'
    '            metric="euclidean", random_state=random_state, verbose=False,\n'
    '        ).fit_transform(X)\n'
    '        perp = int(max(5, min(TSNE_PERPLEXITY, n - 1)))\n'
    '        out_tsne = TSNE(\n'
    '            n_components=2, perplexity=perp, learning_rate="auto", init="pca",\n'
    '            random_state=random_state, verbose=0,\n'
    '        ).fit_transform(X)\n'
    '        tsne_perp = perp\n'
    '    return {\n'
    '        "umap": out_umap, "tsne": out_tsne, "pca": out_pca,\n'
    '        "tsne_perplexity": tsne_perp, "pca_var_pct": pca_var_pct,\n'
    '    }\n'
    '\n'
    '\n'
    'def plot_embedding(\n'
    '    emb: np.ndarray, labels: np.ndarray, out_path: Path, title: str\n'
    ') -> None:\n'
    '    """Scatter plot of 2D embedding colored by cluster."""\n'
    '    fig, ax = plt.subplots(figsize=(8, 6))\n'
    '    for c in np.sort(np.unique(labels)):\n'
    '        m = labels == c\n'
    '        ax.scatter(emb[m, 0], emb[m, 1], s=16, alpha=0.72,\n'
    '                   label=f"C{int(c)} (n={int(m.sum())})")\n'
    '    ax.set_title(title); ax.legend(fontsize=8, ncol=2)\n'
    '    fig.tight_layout()\n'
    '    fig.savefig(out_path, dpi=160)\n'
    '    plt.close(fig)\n'
    '\n'
    '\n'
    'def run_hierarchical_pipeline(\n'
    '    wide_roll: pd.DataFrame,\n'
    '    k_list: list[int],\n'
    '    distance_mode: str,\n'
    '    linkage_method: str,\n'
    '    random_state: int,\n'
    '    suffix: str,\n'
    '    ylabel: str,\n'
    '    years: np.ndarray,\n'
    '    out_dir: Path,\n'
    ') -> tuple[np.ndarray, int, pd.DataFrame]:\n'
    '    """Full pipeline: search k, pick k, fit, plots, CSV. Returns (labels, k_final, search_df)."""'
    '    search_df, D, X_used = hierarchical_search_all_k(\n'
    '        wide_roll, k_list, distance_mode, linkage_method\n'
    '    )\n'
    '    search_path = out_dir / f"trajectory_k_search_metrics_hier_{suffix}.csv"\n'
    '    search_df.to_csv(search_path, index=False)\n'
    '    print(f"k search [{suffix}] (saved {search_path.name}):\\n", search_df.to_string())\n'
    '\n'
    '    k_final, k_strat = pick_best_k_from_metrics(\n'
    '        search_df, FINAL_K_STRATEGY, FINAL_K_OVERRIDE, len(wide_roll)\n'
    '    )\n'
    '    print(f"\\nk_final={k_final} [{suffix}] (strategy={k_strat})")\n'
    '    for _, row in search_df.iterrows():\n'
    '        if pd.notna(row.get("cluster_sizes")):\n'
    '            print(f"  k={int(row[\'k\'])}: {row[\'cluster_sizes\']}")\n'
    '\n'
    '    # Final fit\n'
    '    labels = fit_hierarchical_single_k(\n'
    '        wide_roll, k_final, distance_mode, linkage_method, D, X_used\n'
    '    )\n'
    '\n'
    '    # Diagnostics\n'
    '    plot_hier_k_diagnostics(\n'
    '        search_df, k_final,\n'
    '        out_dir / f"trajectory_k_diagnostics_hier_{suffix}.png",\n'
    '        f"k diagnostics ({suffix})",\n'
    '    )\n'
    '\n'
    '    # Prototypes\n'
    '    plot_prototypes_single(\n'
    '        wide_roll, labels, years,\n'
    '        out_dir / f"trajectory_prototypes_hier_{suffix}.png",\n'
    '        f"Cluster prototypes (k={k_final}, {suffix})",\n'
    '        ylabel=ylabel,\n'
    '    )\n'
    '\n'
    '    # 2D embeddings\n'
    '    emb_pack = fit_2d_embeddings(wide_roll, random_state)\n'
    '    for name, arr in [("umap", emb_pack["umap"]),\n'
    '                        ("tsne", emb_pack["tsne"]),\n'
    '                        ("pca", emb_pack["pca"])]:\n'
    '        if np.any(np.isfinite(arr)):\n'
    '            plot_embedding(\n'
    '                arr, labels,\n'
    '                out_dir / f"trajectory_{name}_hier_{suffix}.png",\n'
    '                f"Trajectory {name.upper()} (k={k_final}, {suffix})",\n'
    '            )\n'
    '\n'
    '    print(f"Cluster sizes [{suffix}]:\\n", pd.Series(labels).value_counts().sort_index())\n'
    '    return labels, k_final, search_df\n'
    '\n'
    '\n'
    '# =============================================================================\n'
    '# 聚类A: log_share 轨迹\n'
    '# =============================================================================\n'
    'print("\\n" + "=" * 60)\n'
    'print("CLUSTERING A: log_share (country share growth pattern)")\n'
    'print("=" * 60)\n'
    'labels_A, k_A, search_A = run_hierarchical_pipeline(\n'
    '    wide_log_share, [int(k) for k in TRAJ_K_RANGE],\n'
    '    HIER_DISTANCE_MODE, HIER_LINKAGE_METHOD,\n'
    '    RANDOM_STATE, "decomposed_A_log_share",\n'
    '    "log(share)", years_all, CATCHUP_ROUND2_DIR,\n'
    ')\n'
    '\n'
    '# =============================================================================\n'
    '# 聚类B: log_frontier 轨迹\n'
    '# =============================================================================\n'
    'print("\\n" + "=" * 60)\n'
    'print("CLUSTERING B: log_frontier (frontier evolution pattern)")\n'
    'print("=" * 60)\n'
    'labels_B, k_B, search_B = run_hierarchical_pipeline(\n'
    '    wide_log_frontier, [int(k) for k in TRAJ_K_RANGE],\n'
    '    HIER_DISTANCE_MODE, HIER_LINKAGE_METHOD,\n'
    '    RANDOM_STATE, "decomposed_B_log_frontier",\n'
    '    "log(frontier)", years_all, CATCHUP_ROUND2_DIR,\n'
    ')\n'
    '\n'
    '# =============================================================================\n'
    '# 聚类C: [Δlog_share, Δlog_frontier] 水平拼接\n'
    '# =============================================================================\n'
    'print("\\n" + "=" * 60)\n'
    'print("CLUSTERING C: [Δlog_share, Δlog_frontier] joint")\n'
    'print("=" * 60)\n'
    'wide_joint = pd.concat([wide_dlog_share, wide_dlog_frontier], axis=1)\n'
    '# wide_joint 有 74 列（37+37），年份数组也要对应扩展\n'
    'years_joint = np.concatenate([years_all, years_all])\n'
    'print("Joint trajectory shape:", wide_joint.shape, "years_joint len:", len(years_joint))\n'
    'labels_C, k_C, search_C = run_hierarchical_pipeline(\n'
    '    wide_joint, [int(k) for k in TRAJ_K_RANGE],\n'
    '    HIER_DISTANCE_MODE, HIER_LINKAGE_METHOD,\n'
    '    RANDOM_STATE, "decomposed_C_joint_deriv",\n'
    '    "Δlog value", years_joint, CATCHUP_ROUND2_DIR,\n'
    ')\n'
))

# =============================================================================
# §9 汇总导出
# =============================================================================
cells.append(md("## 9. 汇总导出"))

cells.append(code(
    '# ---- 组装带聚类标签的 meta 表 ----\n'
    'meta_out = meta.copy()\n'
    'meta_out["trajectory_cluster_A"] = labels_A.astype(int)\n'
    'meta_out["trajectory_cluster_B"] = labels_B.astype(int)\n'
    'meta_out["trajectory_cluster_C"] = labels_C.astype(int)\n'
    'meta_out["quadrant"] = quadrant_df.set_index(meta_out.index)["quadrant"].values\n'
    '\n'
    '# 导出 trajectory_clusters_decomposed.csv\n'
    'clusters_csv = CATCHUP_ROUND2_DIR / "trajectory_clusters_decomposed.csv"\n'
    'meta_out.to_csv(clusters_csv, index=False)\n'
    'print("Saved:", clusters_csv.resolve())\n'
    '\n'
    '# ---- 导出各套聚类的 k 搜索指标 ----\n'
    'search_A.to_csv(\n'
    '    CATCHUP_ROUND2_DIR / "trajectory_k_search_metrics_hier_decomposed_A.csv", index=False\n'
    ')\n'
    'search_B.to_csv(\n'
    '    CATCHUP_ROUND2_DIR / "trajectory_k_search_metrics_hier_decomposed_B.csv", index=False\n'
    ')\n'
    'search_C.to_csv(\n'
    '    CATCHUP_ROUND2_DIR / "trajectory_k_search_metrics_hier_decomposed_C.csv", index=False\n'
    ')\n'
    '\n'
    '# ---- 打印象限 × 聚类C 的交叉表 ----\n'
    'crosstab = pd.crosstab(\n'
    '    meta_out["quadrant"],\n'
    '    meta_out["trajectory_cluster_C"],\n'
    '    margins=True,\n'
    '    margins_name="Total",\n'
    ')\n'
    'print("\\nQuadrant x Cluster_C cross-tab:")\n'
    'print(crosstab)\n'
    '\n'
    '# ---- 解读各聚类C簇的象限构成 ----\n'
    'for c in sorted(meta_out["trajectory_cluster_C"].unique()):\n'
    '    subset = meta_out[meta_out["trajectory_cluster_C"] == c]\n'
    '    print(f"\\nCluster_C={c} (n={len(subset)}):")\n'
    '    print(subset["quadrant"].value_counts())\n'
))

# =============================================================================
# §10 解读与备注
# =============================================================================
cells.append(md(
    "## 10. 解读与备注\n\n"
    "### 聚类C（联合分类）的解释框架\n\n"
    "聚类C对 `[Δlog_share, Δlog_frontier]` 拼接向量聚类，目标是识别追赶类型。\n\n"
    "**分析步骤**：\n"
    "1. 看 `Quadrant x Cluster_C` 交叉表——哪些簇主要落在主动追赶象限？\n"
    "2. 看 `trajectory_prototypes_hier_decomposed_C_joint_deriv.png`——各簇的 Δshare / Δfrontier 均值曲线趋势\n"
    "3. 对比聚类A（只看份额）和聚类B（只看前沿）是否与聚类C的象限分布一致\n\n"
    "### 与原 hierarchical notebook 的关系\n\n"
    "- 本 notebook 复用了 `time_series_hierarchical.ipynb` 的数据加载、面板构建和层次聚类工具函数\n"
    "- 新增：乘积分解 → 四套轨迹 → 三套独立聚类\n"
    "- 原 `ratio` 轨迹聚类（hierarchical）仍然有效，可与本 notebook 的分解结果对照\n\n"
    "### 已知局限\n\n"
    "- log 变换对 share=0 的处理：填充 1e-10 等价于假设\"零发文国家有极微弱存在\"，是人为假设\n"
    "- 导数轨迹的头部年份（t=0）因差分而缺失，rolling 后实际有效年份从 `DECOMP_DERIV_ROLLING_WINDOW` 开始\n"
    "- 象限分界采用中位数，若数据高度偏态可能不适用\n"
    "- 本 notebook 固定使用 DTW 距离模式（与 hierarchical 的默认参数一致）"
))

# =============================================================================
# 写入 notebook
# =============================================================================
nb = nbf.new_notebook(
    metadata={
        "kernelspec": {
            "display_name": "catch-up (uv venv)",
            "language": "python",
            "name": "catchup-venv",
        },
        "language_info": {"name": "python", "version": "3.10.0"},
    },
    cells=cells,
)
nbformat.write(nb, OUT_NB)
print("Wrote", OUT_NB)
